// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/shop/shop.proto

package com_example_srv_shop

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SearchKey            string   `protobuf:"bytes,4,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	Disable              bool     `protobuf:"varint,5,opt,name=disable,proto3" json:"disable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_846ffd47eaa9ea2a, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Request) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *Request) GetSearchKey() string {
	if m != nil {
		return m.SearchKey
	}
	return ""
}

func (m *Request) GetDisable() bool {
	if m != nil {
		return m.Disable
	}
	return false
}

type Response struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_846ffd47eaa9ea2a, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 店铺列表
type ShopListItem struct {
	Shops                []*ShopDetail `protobuf:"bytes,1,rep,name=shops,proto3" json:"shops,omitempty"`
	Count                int32         `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ShopListItem) Reset()         { *m = ShopListItem{} }
func (m *ShopListItem) String() string { return proto.CompactTextString(m) }
func (*ShopListItem) ProtoMessage()    {}
func (*ShopListItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_846ffd47eaa9ea2a, []int{2}
}

func (m *ShopListItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopListItem.Unmarshal(m, b)
}
func (m *ShopListItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopListItem.Marshal(b, m, deterministic)
}
func (m *ShopListItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopListItem.Merge(m, src)
}
func (m *ShopListItem) XXX_Size() int {
	return xxx_messageInfo_ShopListItem.Size(m)
}
func (m *ShopListItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopListItem.DiscardUnknown(m)
}

var xxx_messageInfo_ShopListItem proto.InternalMessageInfo

func (m *ShopListItem) GetShops() []*ShopDetail {
	if m != nil {
		return m.Shops
	}
	return nil
}

func (m *ShopListItem) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 店铺详情
type ShopDetail struct {
	ShopName             string   `protobuf:"bytes,1,opt,name=shop_name,json=shopName,proto3" json:"shop_name,omitempty"`
	BsNumber             int32    `protobuf:"varint,2,opt,name=bs_number,json=bsNumber,proto3" json:"bs_number,omitempty"`
	IsActive             bool     `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Addr                 string   `protobuf:"bytes,4,opt,name=addr,proto3" json:"addr,omitempty"`
	Lat                  float32  `protobuf:"fixed32,5,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float32  `protobuf:"fixed32,6,opt,name=lon,proto3" json:"lon,omitempty"`
	Phone                string   `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Industry             string   `protobuf:"bytes,8,opt,name=industry,proto3" json:"industry,omitempty"`
	IndustryId           uint32   `protobuf:"varint,9,opt,name=industry_id,json=industryId,proto3" json:"industry_id,omitempty"`
	RunningPeriod        []string `protobuf:"bytes,10,rep,name=running_period,json=runningPeriod,proto3" json:"running_period,omitempty"`
	Md5List              []string `protobuf:"bytes,11,rep,name=md5_list,json=md5List,proto3" json:"md5_list,omitempty"`
	AppUserId            uint32   `protobuf:"varint,12,opt,name=app_user_id,json=appUserId,proto3" json:"app_user_id,omitempty"`
	RegionId             uint32   `protobuf:"varint,13,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Region               string   `protobuf:"bytes,14,opt,name=region,proto3" json:"region,omitempty"`
	Id                   uint32   `protobuf:"varint,15,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopDetail) Reset()         { *m = ShopDetail{} }
func (m *ShopDetail) String() string { return proto.CompactTextString(m) }
func (*ShopDetail) ProtoMessage()    {}
func (*ShopDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_846ffd47eaa9ea2a, []int{3}
}

func (m *ShopDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopDetail.Unmarshal(m, b)
}
func (m *ShopDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopDetail.Marshal(b, m, deterministic)
}
func (m *ShopDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopDetail.Merge(m, src)
}
func (m *ShopDetail) XXX_Size() int {
	return xxx_messageInfo_ShopDetail.Size(m)
}
func (m *ShopDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ShopDetail proto.InternalMessageInfo

func (m *ShopDetail) GetShopName() string {
	if m != nil {
		return m.ShopName
	}
	return ""
}

func (m *ShopDetail) GetBsNumber() int32 {
	if m != nil {
		return m.BsNumber
	}
	return 0
}

func (m *ShopDetail) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *ShopDetail) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ShopDetail) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *ShopDetail) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *ShopDetail) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ShopDetail) GetIndustry() string {
	if m != nil {
		return m.Industry
	}
	return ""
}

func (m *ShopDetail) GetIndustryId() uint32 {
	if m != nil {
		return m.IndustryId
	}
	return 0
}

func (m *ShopDetail) GetRunningPeriod() []string {
	if m != nil {
		return m.RunningPeriod
	}
	return nil
}

func (m *ShopDetail) GetMd5List() []string {
	if m != nil {
		return m.Md5List
	}
	return nil
}

func (m *ShopDetail) GetAppUserId() uint32 {
	if m != nil {
		return m.AppUserId
	}
	return 0
}

func (m *ShopDetail) GetRegionId() uint32 {
	if m != nil {
		return m.RegionId
	}
	return 0
}

func (m *ShopDetail) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *ShopDetail) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "com.example.srv.shop.Request")
	proto.RegisterType((*Response)(nil), "com.example.srv.shop.Response")
	proto.RegisterType((*ShopListItem)(nil), "com.example.srv.shop.ShopListItem")
	proto.RegisterType((*ShopDetail)(nil), "com.example.srv.shop.ShopDetail")
}

func init() { proto.RegisterFile("proto/shop/shop.proto", fileDescriptor_846ffd47eaa9ea2a) }

var fileDescriptor_846ffd47eaa9ea2a = []byte{
	// 542 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x51, 0x6b, 0xd4, 0x40,
	0x10, 0x6e, 0xee, 0x7a, 0x97, 0x64, 0xae, 0xad, 0xb2, 0x54, 0x59, 0x4f, 0x5a, 0x43, 0x40, 0xc8,
	0x53, 0x84, 0x4a, 0x7d, 0x57, 0x0b, 0x72, 0x5a, 0x8b, 0xa4, 0xf8, 0x26, 0x84, 0xbd, 0xdb, 0xe1,
	0x6e, 0xf1, 0xb2, 0xbb, 0xee, 0x6e, 0x8a, 0xed, 0xab, 0xbf, 0xc1, 0x7f, 0xe5, 0x8f, 0x92, 0xdd,
	0x24, 0x08, 0xd2, 0x72, 0x2f, 0x77, 0xf3, 0x7d, 0x33, 0x99, 0xfd, 0xe6, 0x9b, 0x6c, 0xe0, 0x89,
	0x36, 0xca, 0xa9, 0x57, 0x76, 0xa3, 0x74, 0xf8, 0x29, 0x03, 0x26, 0xc7, 0x2b, 0xd5, 0x94, 0xf8,
	0x93, 0x35, 0x7a, 0x8b, 0xa5, 0x35, 0x37, 0xa5, 0xcf, 0xe5, 0xbf, 0x22, 0x88, 0x2b, 0xfc, 0xd1,
	0xa2, 0x75, 0xe4, 0x08, 0x46, 0x82, 0xd3, 0x28, 0x8b, 0x8a, 0xc3, 0x6a, 0x24, 0x38, 0x21, 0xb0,
	0xaf, 0xd9, 0x1a, 0xe9, 0x28, 0x8b, 0x8a, 0x49, 0x15, 0x62, 0xf2, 0x1c, 0x52, 0xff, 0x5f, 0x5b,
	0x71, 0x87, 0x74, 0x1c, 0x12, 0x89, 0x27, 0xae, 0xc5, 0x1d, 0x92, 0x13, 0x00, 0x8b, 0xcc, 0xac,
	0x36, 0xf5, 0x77, 0xbc, 0xa5, 0xfb, 0x59, 0x54, 0xa4, 0x55, 0xda, 0x31, 0x9f, 0xf0, 0x96, 0x50,
	0x88, 0xb9, 0xb0, 0x6c, 0xb9, 0x45, 0x3a, 0xc9, 0xa2, 0x22, 0xa9, 0x06, 0x98, 0xcf, 0x21, 0xa9,
	0xd0, 0x6a, 0x25, 0x2d, 0xfe, 0xaf, 0x22, 0xff, 0x06, 0x07, 0xd7, 0x1b, 0xa5, 0x2f, 0x85, 0x75,
	0x0b, 0x87, 0x0d, 0x79, 0x03, 0x13, 0xaf, 0xdc, 0xd2, 0x28, 0x1b, 0x17, 0xb3, 0xb3, 0xac, 0xbc,
	0x6f, 0xae, 0xd2, 0x3f, 0x72, 0x81, 0x8e, 0x89, 0x6d, 0xd5, 0x95, 0x93, 0x63, 0x98, 0xac, 0x54,
	0x2b, 0x5d, 0x3f, 0x4e, 0x07, 0xf2, 0xdf, 0x63, 0x80, 0x7f, 0xb5, 0x7e, 0x3c, 0x5f, 0x5d, 0x4b,
	0xd6, 0x60, 0xd0, 0x90, 0x56, 0x89, 0x27, 0xae, 0x58, 0x13, 0x66, 0x5f, 0xda, 0x5a, 0xb6, 0xcd,
	0x12, 0x4d, 0xdf, 0x25, 0x59, 0xda, 0xab, 0x80, 0x7d, 0x52, 0xd8, 0x9a, 0xad, 0x9c, 0xb8, 0xe9,
	0x8c, 0x49, 0xaa, 0x44, 0xd8, 0xb7, 0x01, 0x7b, 0x27, 0x19, 0xe7, 0xa6, 0xb7, 0x24, 0xc4, 0xe4,
	0x31, 0x8c, 0xb7, 0xcc, 0x05, 0x27, 0x46, 0x95, 0x0f, 0x03, 0xa3, 0x24, 0x9d, 0xf6, 0x8c, 0x92,
	0x5e, 0xb3, 0xde, 0x28, 0x89, 0x34, 0x0e, 0x0f, 0x76, 0x80, 0xcc, 0x21, 0x11, 0x92, 0xb7, 0xd6,
	0x99, 0x5b, 0x9a, 0x74, 0x1a, 0x07, 0x4c, 0x5e, 0xc0, 0x6c, 0x88, 0x6b, 0xc1, 0x69, 0x1a, 0x6c,
	0x84, 0x81, 0x5a, 0x70, 0xf2, 0x12, 0x8e, 0x4c, 0x2b, 0xa5, 0x90, 0xeb, 0x5a, 0xa3, 0x11, 0x8a,
	0x53, 0xc8, 0xc6, 0x45, 0x5a, 0x1d, 0xf6, 0xec, 0x97, 0x40, 0x92, 0x67, 0x90, 0x34, 0xfc, 0xbc,
	0xde, 0x0a, 0xeb, 0xe8, 0x2c, 0x14, 0xc4, 0x0d, 0x3f, 0xf7, 0x4b, 0x20, 0xa7, 0x30, 0x63, 0x5a,
	0xd7, 0xad, 0x45, 0xe3, 0x8f, 0x38, 0x08, 0x47, 0xa4, 0x4c, 0xeb, 0xaf, 0x16, 0xcd, 0x82, 0x7b,
	0x27, 0x0c, 0xae, 0x85, 0x92, 0x3e, 0x7b, 0x18, 0xb2, 0x49, 0x47, 0x2c, 0x38, 0x79, 0x0a, 0xd3,
	0x2e, 0xa6, 0x47, 0x41, 0x79, 0x8f, 0xfa, 0xad, 0x3f, 0x1a, 0xb6, 0x7e, 0xf6, 0x67, 0x04, 0xc4,
	0xef, 0xe5, 0x33, 0x93, 0x6c, 0x8d, 0xe6, 0x1a, 0xcd, 0x8d, 0x58, 0x21, 0xb9, 0x84, 0xe9, 0x7b,
	0x83, 0xcc, 0x21, 0xd9, 0xb9, 0xf7, 0xf9, 0xe9, 0xfd, 0x15, 0xc3, 0x8b, 0x96, 0xef, 0x91, 0x2b,
	0x88, 0x3f, 0xa0, 0x0b, 0x43, 0x9d, 0x3c, 0x54, 0x1c, 0xae, 0xc6, 0x3c, 0x7f, 0xf8, 0xb4, 0xe1,
	0xc5, 0xcc, 0xf7, 0xc8, 0x65, 0xe8, 0xf7, 0xce, 0xdb, 0xbc, 0xa3, 0xdf, 0x4e, 0xf5, 0xf9, 0x1e,
	0xf9, 0x08, 0xf1, 0x45, 0x77, 0x3f, 0x76, 0x75, 0xdb, 0x39, 0xe9, 0x72, 0x1a, 0xbe, 0x01, 0xaf,
	0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x17, 0xc4, 0xee, 0x8e, 0x1c, 0x04, 0x00, 0x00,
}
