// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/adminUser/adminUser.proto

package com_example_srv_adminUser

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for AdminUserService service

type AdminUserService interface {
	Insert(ctx context.Context, in *AdminUser, opts ...client.CallOption) (*Response, error)
	GetById(ctx context.Context, in *Request, opts ...client.CallOption) (*AdminUser, error)
	UpdateById(ctx context.Context, in *AdminUser, opts ...client.CallOption) (*Response, error)
}

type adminUserService struct {
	c    client.Client
	name string
}

func NewAdminUserService(name string, c client.Client) AdminUserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "com.example.srv.adminUser"
	}
	return &adminUserService{
		c:    c,
		name: name,
	}
}

func (c *adminUserService) Insert(ctx context.Context, in *AdminUser, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "AdminUserService.Insert", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminUserService) GetById(ctx context.Context, in *Request, opts ...client.CallOption) (*AdminUser, error) {
	req := c.c.NewRequest(c.name, "AdminUserService.GetById", in)
	out := new(AdminUser)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminUserService) UpdateById(ctx context.Context, in *AdminUser, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "AdminUserService.UpdateById", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AdminUserService service

type AdminUserServiceHandler interface {
	Insert(context.Context, *AdminUser, *Response) error
	GetById(context.Context, *Request, *AdminUser) error
	UpdateById(context.Context, *AdminUser, *Response) error
}

func RegisterAdminUserServiceHandler(s server.Server, hdlr AdminUserServiceHandler, opts ...server.HandlerOption) error {
	type adminUserService interface {
		Insert(ctx context.Context, in *AdminUser, out *Response) error
		GetById(ctx context.Context, in *Request, out *AdminUser) error
		UpdateById(ctx context.Context, in *AdminUser, out *Response) error
	}
	type AdminUserService struct {
		adminUserService
	}
	h := &adminUserServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&AdminUserService{h}, opts...))
}

type adminUserServiceHandler struct {
	AdminUserServiceHandler
}

func (h *adminUserServiceHandler) Insert(ctx context.Context, in *AdminUser, out *Response) error {
	return h.AdminUserServiceHandler.Insert(ctx, in, out)
}

func (h *adminUserServiceHandler) GetById(ctx context.Context, in *Request, out *AdminUser) error {
	return h.AdminUserServiceHandler.GetById(ctx, in, out)
}

func (h *adminUserServiceHandler) UpdateById(ctx context.Context, in *AdminUser, out *Response) error {
	return h.AdminUserServiceHandler.UpdateById(ctx, in, out)
}
