// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/adminUser/adminUser.proto

package com_infinite_srv_adminUser

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AdminUser struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	RoleId               int64    `protobuf:"varint,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Remark               string   `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	IsSuper              bool     `protobuf:"varint,5,opt,name=is_super,json=isSuper,proto3" json:"is_super,omitempty"`
	IsActive             bool     `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Password             string   `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminUser) Reset()         { *m = AdminUser{} }
func (m *AdminUser) String() string { return proto.CompactTextString(m) }
func (*AdminUser) ProtoMessage()    {}
func (*AdminUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90ecf4034ec0939, []int{0}
}

func (m *AdminUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminUser.Unmarshal(m, b)
}
func (m *AdminUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminUser.Marshal(b, m, deterministic)
}
func (m *AdminUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUser.Merge(m, src)
}
func (m *AdminUser) XXX_Size() int {
	return xxx_messageInfo_AdminUser.Size(m)
}
func (m *AdminUser) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUser.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUser proto.InternalMessageInfo

func (m *AdminUser) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AdminUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AdminUser) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *AdminUser) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *AdminUser) GetIsSuper() bool {
	if m != nil {
		return m.IsSuper
	}
	return false
}

func (m *AdminUser) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *AdminUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90ecf4034ec0939, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type Request struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_b90ecf4034ec0939, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*AdminUser)(nil), "com.infinite.srv.adminUser.AdminUser")
	proto.RegisterType((*Response)(nil), "com.infinite.srv.adminUser.Response")
	proto.RegisterType((*Request)(nil), "com.infinite.srv.adminUser.Request")
}

func init() { proto.RegisterFile("proto/adminUser/adminUser.proto", fileDescriptor_b90ecf4034ec0939) }

var fileDescriptor_b90ecf4034ec0939 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x9b, 0x54, 0x93, 0x74, 0x0e, 0x22, 0x73, 0xd0, 0x6d, 0x3c, 0x58, 0xa2, 0x42, 0x4f,
	0x11, 0xf4, 0x09, 0xea, 0x45, 0x7a, 0x4d, 0x29, 0x3d, 0x78, 0x28, 0xb1, 0x3b, 0xc2, 0xa0, 0xc9,
	0xc6, 0x9d, 0x6d, 0xc5, 0xc7, 0xf1, 0x3d, 0x7c, 0x38, 0xc9, 0x6a, 0x23, 0x08, 0x16, 0x0f, 0xde,
	0xf6, 0x63, 0xe6, 0xdf, 0xfd, 0x66, 0x19, 0x38, 0x6d, 0xac, 0x71, 0xe6, 0xb2, 0xd4, 0x15, 0xd7,
	0x73, 0x21, 0xfb, 0x7d, 0xca, 0x7d, 0x05, 0xd3, 0x95, 0xa9, 0x72, 0xae, 0x1f, 0xb8, 0x66, 0x47,
	0xb9, 0xd8, 0x4d, 0xde, 0x75, 0x64, 0xef, 0x01, 0x0c, 0x26, 0x5b, 0xc2, 0x03, 0x08, 0x59, 0xab,
	0x60, 0x14, 0x8c, 0xfb, 0x45, 0xc8, 0x1a, 0x53, 0x48, 0xd6, 0x42, 0xb6, 0x2e, 0x2b, 0x52, 0xe1,
	0x28, 0x18, 0x0f, 0x8a, 0x8e, 0xf1, 0x18, 0x62, 0x6b, 0x9e, 0x68, 0xc9, 0x5a, 0xf5, 0x7d, 0x20,
	0x6a, 0x71, 0xaa, 0xf1, 0x08, 0x22, 0x4b, 0x55, 0x69, 0x1f, 0xd5, 0x9e, 0x8f, 0x7c, 0x11, 0x0e,
	0x21, 0x61, 0x59, 0xca, 0xba, 0x21, 0xab, 0xf6, 0x47, 0xc1, 0x38, 0x29, 0x62, 0x96, 0x59, 0x8b,
	0x78, 0x02, 0x03, 0x96, 0x65, 0xb9, 0x72, 0xbc, 0x21, 0x15, 0xf9, 0x5a, 0xc2, 0x32, 0xf1, 0xdc,
	0x4a, 0x34, 0xa5, 0xc8, 0x8b, 0xb1, 0x5a, 0xc5, 0x9f, 0x12, 0x5b, 0xce, 0x00, 0x92, 0x82, 0xa4,
	0x31, 0xb5, 0x50, 0x36, 0x84, 0xb8, 0xa0, 0xe7, 0x35, 0x89, 0xfb, 0x39, 0xc7, 0xd5, 0x5b, 0x08,
	0x87, 0xdd, 0x94, 0x33, 0xb2, 0x1b, 0x5e, 0x11, 0x2e, 0x20, 0x9a, 0xd6, 0x42, 0xd6, 0xe1, 0x45,
	0xfe, 0xfb, 0x0f, 0xe5, 0x5d, 0x2e, 0x3d, 0xdf, 0xd5, 0xd6, 0x69, 0xf4, 0x70, 0x01, 0xf1, 0x2d,
	0xb9, 0x9b, 0xd7, 0xa9, 0xc6, 0xb3, 0xdd, 0x11, 0x6f, 0x9b, 0xfe, 0xed, 0xf9, 0xac, 0x87, 0x77,
	0x00, 0xf3, 0x46, 0x97, 0x8e, 0xfc, 0xdd, 0xff, 0x6b, 0x7d, 0x1f, 0xf9, 0x65, 0xb9, 0xfe, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x82, 0x91, 0x54, 0xb2, 0x4f, 0x02, 0x00, 0x00,
}
